"""Configuration loading and deep-merge.

Why a single YAML + override files rather than CLI flags for everything: the plan
(§16) requires that every displayed number trace to a reproducible configuration.
A run records the fully-resolved config it used (`shoal.runlog`), so a slide can be
regenerated byte-for-byte months later. CLI flags are reserved for the few things
that genuinely change per invocation (clip path, device, frame cap).
"""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG_PATH = REPO_ROOT / "config" / "pipeline.yaml"


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge ``override`` into a copy of ``base``.

    Mappings merge key-wise; every other type (lists included) replaces wholesale.
    Lists replace rather than concatenate because the config lists here are
    closed sets (e.g. ``export.formats``) where "add one" and "replace all" would
    be ambiguous.
    """
    out = copy.deepcopy(base)
    for key, val in override.items():
        if key in out and isinstance(out[key], dict) and isinstance(val, dict):
            out[key] = _deep_merge(out[key], val)
        else:
            out[key] = copy.deepcopy(val)
    return out


class Config:
    """Dotted-path read-only view over the resolved config dict."""

    def __init__(self, data: dict[str, Any], sources: list[Path]):
        self._data = data
        self.sources = sources

    def __getitem__(self, key: str) -> Any:
        return self._data[key]

    def get(self, dotted: str, default: Any = None) -> Any:
        """``cfg.get("restore.gate_threshold")`` -> value or ``default``."""
        node: Any = self._data
        for part in dotted.split("."):
            if not isinstance(node, dict) or part not in node:
                return default
            node = node[part]
        return node

    def require(self, dotted: str) -> Any:
        sentinel = object()
        val = self.get(dotted, sentinel)
        if val is sentinel:
            raise KeyError(f"required config key missing: {dotted}")
        return val

    def as_dict(self) -> dict[str, Any]:
        return copy.deepcopy(self._data)


def load_config(
    path: str | Path | None = None,
    overrides: list[str | Path] | None = None,
    inline: dict[str, Any] | None = None,
) -> Config:
    """Load the base config, then deep-merge each override file, then ``inline``.

    ``inline`` is where resolved CLI arguments land so they win over everything.
    """
    base_path = Path(path) if path else DEFAULT_CONFIG_PATH
    with open(base_path) as fh:
        data = yaml.safe_load(fh) or {}
    sources = [base_path]

    for ov in overrides or []:
        ov_path = Path(ov)
        with open(ov_path) as fh:
            data = _deep_merge(data, yaml.safe_load(fh) or {})
        sources.append(ov_path)

    if inline:
        data = _deep_merge(data, inline)

    return Config(data, sources)


def resolve_device(requested: str) -> str:
    """Map ``auto`` -> ``cuda``/``cpu``. The actual choice is logged by the caller.

    Kept here (not in the pipeline) so ``shoal.check`` and every entry point agree
    on one resolution rule.
    """
    requested = (requested or "auto").lower()
    if requested != "auto":
        return requested
    try:
        import torch

        return "cuda" if torch.cuda.is_available() else "cpu"
    except Exception:
        return "cpu"
